---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghew9261/mamaholding.net/public_html
    - cd /home/ghew9261/mamaholding.net/mamaholding-website
    - npm install
    - npm run build
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r out/* $DEPLOYPATH/
    - /bin/cp public/.htaccess $DEPLOYPATH/ 2>/dev/null || true