---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghew9261/mamaholding.net/public_html
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -r /home/ghew9261/mamaholding.net/mamaholding-website/* $DEPLOYPATH/
    - /bin/cp /home/ghew9261/mamaholding.net/mamaholding-website/public/.htaccess $DEPLOYPATH/ 2>/dev/null || true