---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghew9261/mamaholding.net/public_html
    - /bin/cp -r mamaholding-website/* $DEPLOYPATH/
    - /bin/cp mamaholding-website/public/.htaccess $DEPLOYPATH/ 2>/dev/null || true
