---
deployment:
  tasks:
    - export DEPLOYPATH=/home/ghew9261/mamaholding.net/public_html
    - /bin/cp -r /home/ghew9261/mamaholding.net/mamaholding-website/* $DEPLOYPATH/
    - /bin/cp -r /home/ghew9261/mamaholding.net/mamaholding-website/.[^.]* $DEPLOYPATH/ 2>/dev/null || true
